name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        shell: pwsh
        run: choco install ffmpeg -y

      - name: Install Python dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r aula_fazer_teste/requirements.txt
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: '1'

      - name: Static compilation check
        shell: pwsh
        run: python -m compileall aula_fazer_teste
